config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/', :sitemap => false

  get 'results/new'

  get 'results/create'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  get 'welcome/index'

  resources :events
  resources :live_rooms

  resources :matches do
    resources :comments
    resource :result
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_playerships
  has_many :players, :through => :event_playerships
  has_many :matches
end

app/models/match.rb
class Match < ActiveRecord::Base
  #before_validation :default_values

  has_many :match_liveroomships
  has_many :live_rooms, :through => :match_liveroomships
  has_one :result
  has_many :comments

  accepts_nested_attributes_for :result
  #accepts_nested_attributes_for :match_liveroomships

  belongs_to :event
  belongs_to :player1, :class_name => "User"
  belongs_to :player2, :class_name => "User"
  #belongs_to :winner, :class_name => "Player"
  #belongs_to :winner, foregin_key: 'winner_id' :class_name => "Player"
  #def all_players
    #Player.where(id: [self.player1_id, self.player2_id])
  #end

  validates :name, presence: true
  validates :time, presence: true
  validates :event_id, presence: true
  #validates :player1_id, presence: true
  #validates :player2_id, presence: true

  #def winner_str
    #@winner_str
  #end

  #def winner_str= (str)
    #@winner_str = str
    #if @winner_str == 'match.winner.first'
      #winner_id = player1_id
    #end
    #if @winner_str == 'match.winner.second'
      #winner_id = player2_id
    #end
  #end

  private
  #def default_values
    #self.status ||= 'match.status.tobedone'
  #end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @matches = Match.where(event: @event)
    @match = Match.new(event: @event)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :introduction, :orgnization, player_ids:[])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t("event.name")
    = f.text_field :name, class: 'form-control', placeholder: t('event.name')
  .form-group
    = f.label t("event.orgnization")
    = f.text_field :orgnization, class: 'form-control', placeholder: t('event.orgnization')
  .form-group
    = f.label t('event.introduction')
    -#= f.text_field :introduction, class: 'form-control', placeholder: t('event.introduction')
    = f.text_area :introduction, class: 'form-control', placeholder: t('event.introduction'), rows: '3'
  -#.form-group
    -#= f.label t('event.playerlist')
    -#= f.select :player_ids, User.all.collect{|x| [x.name, x.id]}, {}, {class: "form-control" , :multiple => true}
  .actions
    = f.submit t('user.save'), class: "btn btn-primary"

app/views/events/_match_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t('match.time')
    = f.datetime_select :time, class: 'form-control'

  .form-group
    = f.label t('match.name')
    = f.text_field :name, class: 'form-control', placeholder: t('match.name')

  .form-group
    -#= f.label t("match.event")
    -#=f.collection_select :event_id, [@event], :id, :name, {}, {class: "form-control"}
    =f.collection_select :event_id, [@event], :id, :name, {}, {style: "visibility:hidden"}

  -#.form-group
    -#= f.label t("match.player1")
    -#=f.collection_select :player1_id, @event.players, :id, :name, {}, {class: "form-control"}

  -#.form-group
    -#= f.label t("match.player2")
    -#=f.collection_select :player2_id, @event.players, :id, :name, {}, {class: "form-control"}

  .form-group
    = f.label t('match.liverooms')
    = f.select :live_room_ids, LiveRoom.all.collect{|x| [x.name, x.id]}, {}, {class: "form-control" , :multiple => true}

  .actions
    = f.submit t('user.save'), class: "btn btn-primary"

app/views/events/edit.html.haml
- provide :title, t("event.edit")
%h1= t("event.edit")+" "+@event.name

= render 'form'

.center
  = link_to t("user.show"), @event, class: "btn btn-default"
  \|
  = link_to t("user.back"), events_path, class: "btn btn-default"

app/views/events/index.html.haml
- provide :title, t("event.index")

%table.table.table-hover
  %thead
    %tr
      %th= t('event.name')
      %th= t('event.orgnization')
      -#%th= t('event.introduction')
      -#%th= t("user.created_at")
      -#%th= t("user.updated_at")
      -if can? :manage, Event
        %th= t("user.operations")

  %tbody
    - @events.each do |event|
      %tr
        %td
          =link_to event_path(event) do
            =event.name
        %td= event.orgnization
        -#%td= event.introduction
        -#%td= l event.created_at
        -#%td= l event.updated_at
        -if can? :manage, Event
          %td
            %ul.list-inline
              %li= link_to t("user.edit"), edit_event_path(event)
              %li= link_to t("user.destroy"), event, method: :delete, data: {confirm: "Are you sure?"}
%br

-if can? :manage, Event
  =link_to t("event.new"), new_event_path, class: "btn btn-lg btn-primary", role: "button"

app/views/events/new.html.haml
%h1= t('event.new')

= render 'form'

= link_to t('user.back'), events_path

app/views/events/show.html.haml
%p#notice= notice

.center-block
  %h1= @event.name 
%p= @event.introduction

-#.panel.panel-info
  -#.panel-heading= t('event.introduction')
  -#-#.panel-body
  -#%table.table.table-hover.table-bordered
    -#%thead
      -#%tr
        -#%th= t('user.info_name')
        -#%th= t('user.info_content')
    -#%tbody
      -#%tr
        -#%td= t('event.name')
        -#%td= @event.name
      -#%tr
        -#%td= t('event.orgnization')
        -#%td= @event.orgnization
      -#%tr
        -#%td= t('event.introduction')
        -#%td= @event.introduction

-#.panel.panel-info
  -#.panel-heading= t('event.score_board')
  -#-#.panel-body
  -#%table.table.table-hover.table-bordered
    -#%thead
      -#%tr
        -#%th= t('event.player_name')
        -#%th= t('event.match_number')
        -#%th= t('event.win_match_number')
        -#%th= t('event.score')
    -#%tbody
      -#- @event.players.each do |player|
        -#%tr
          -#%td= player.name
          -#-#%td
            -#-#=link_to user_path(player) do
              -#-#=player.name
          -#-@all_event_matches = player.all_event_matches(@event.id)
          -#-@all_event_win_matches = player.all_event_win_matches(@event.id)
          -#%td= @all_event_matches.size
          -#%td= @all_event_win_matches.size
          -#%td= @all_event_win_matches.size*3

.panel.panel-info
  .panel-heading= t('event.matches')
  -#.panel-body
  %table.table.table-hover
    %thead
      %tr
        %th= t('match.name')
        -#%th= t('match.event')
        -#%th= t('match.players')
        %th= t('match.time')
        %th= t('match.status_name')
        -if can? :manage, Match
          %th= t("user.operations")
  
    %tbody
      - @matches.each do |match|
        %tr
          %td
            =link_to match_path(match) do
              =match.name
          -#%td
            -#=link_to event_path(match.event) do
              -#=match.event.name
          -#%td
            -#=link_to user_path(match.player1) do
              -#=match.player1.name
            -#VS 
            -#=link_to user_path(match.player2) do
              -#=match.player2.name
          %td= l match.time
          %td= match.result ? t('match.status.done') : t('match.status.tobedone')
          -#-if match.result
            -#%td= t('match.status.done')
            -#%td
              -#-#=link_to match_result_path(match) do
              -#=match.result.player1_score
              -#\:
              -#=match.result.player2_score
          -#-else
            -#%td= t('match.status.tobedone')
          -if can? :manage, Match
            %td
              %ul.list-inline
                %li= link_to t("user.edit"), edit_match_path(match)
                %li= link_to t("user.destroy"), match, method: :delete, data: {confirm: "Are you sure?"}

-if can? :manage, Match
  .panel.panel-info
    .panel-heading= t('event.new_match')
    .panel-body
      = render 'events/match_form'

.center
  -if can? :manage, Event
    = link_to t("user.edit"), edit_event_path(@event), class: "btn btn-default"
    -#\|
  -#= link_to t("user.back"), events_path, class: "btn btn-default"