config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/', :sitemap => false

  get 'results/new'

  get 'results/create'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  get 'welcome/index'

  resources :events
  resources :live_rooms

  resources :matches do
    resources :comments
    resource :result
  end

end

app/models/match.rb
class Match < ActiveRecord::Base
  #before_validation :default_values

  has_many :match_liveroomships
  has_many :live_rooms, :through => :match_liveroomships
  has_one :result
  has_many :comments

  accepts_nested_attributes_for :result
  #accepts_nested_attributes_for :match_liveroomships

  belongs_to :event
  belongs_to :player1, :class_name => "User"
  belongs_to :player2, :class_name => "User"
  #belongs_to :winner, :class_name => "Player"
  #belongs_to :winner, foregin_key: 'winner_id' :class_name => "Player"
  #def all_players
    #Player.where(id: [self.player1_id, self.player2_id])
  #end

  validates :name, presence: true
  validates :time, presence: true
  validates :event_id, presence: true
  #validates :player1_id, presence: true
  #validates :player2_id, presence: true

  #def winner_str
    #@winner_str
  #end

  #def winner_str= (str)
    #@winner_str = str
    #if @winner_str == 'match.winner.first'
      #winner_id = player1_id
    #end
    #if @winner_str == 'match.winner.second'
      #winner_id = player2_id
    #end
  #end

  private
  #def default_values
    #self.status ||= 'match.status.tobedone'
  #end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.order(time: :desc)
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
    #@match.build_result
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        #format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.html { redirect_to @match.event, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        #format.html { render :new }
        @event = @match.event
        @matches = Match.where(event: @event)
        format.html { render 'events/show'}
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:time, :event_id, :player1_id, :player2_id, :name, live_room_ids:[], result_attributes: [:player1_score, :player2_score, :description, :videourl])
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.haml
= form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label t('match.time')
    -#= f.date_select :time, class: 'form-control'
    -#= f.time_select :time, :ignore_date => true, class: 'form-control'
    = f.datetime_select :time, class: 'form-control'

  .form-group
    = f.label t('match.name')
    = f.text_field :name, class: 'form-control', placeholder: t('match.name')

  .form-group
    = f.label t("match.event")
    =f.collection_select :event_id, Event.all, :id, :name, {}, {class: "form-control"}

  -#.form-group
    -#= f.label t("match.player1")
    -#=f.collection_select :player1_id, User.all, :id, :name, {}, {class: "form-control"}

  -#.form-group
    -#= f.label t("match.player2")
    -#=f.collection_select :player2_id, User.all, :id, :name, {}, {class: "form-control"}

  .form-group
    = f.label t('match.liverooms')
    = f.select :live_room_ids, LiveRoom.all.collect{|x| [x.name, x.id]}, {}, {class: "form-control" , :multiple => true}
    -#= f.simple_fields_for :match_liveroomships do |match_liveromm|
      -#= render 'match_liveroom_fields', :f => project_tag
    -#= link_to_add_association 'add a liveroom', f, :match_liveroomships

  -#=fields_for :result do |result_fields|
    -#.form-group
      -#=result_fields.label @match.player1.name
      -#= result_fields.text_field :player1_score, class: 'form-control', placeholder: t('result.player1_score')
    -#.form-group
      -#=result_fields.label @match.player2.name
      -#= result_fields.text_field :player2_score, class: 'form-control', placeholder: t('result.player2_score')
    -#.form-group
      -#=result_fields.label t('result.description')
      -#= result_fields.text_field :description, class: 'form-control', placeholder: t('result.description')
    -#.form-group
      -#=result_fields.label t('result.videourl')
      -#= result_fields.text_field :videourl, class: 'form-control', placeholder: t('result.videourl')

  .actions
    = f.submit t('user.save'), class: "btn btn-primary"

app/views/matches/_match_liveroom_fields.html.haml
.nested-fields.project-tag-fields
  #liveroom_from_list
    = f.association :live_room, :collection => LiveRoom.all(:order => 'name'), :prompt => 'Choose an existing tag'
  -#= link_to_add_association 'or create a new live_room', f, :live_room
  -#= link_to_remove_association "remove live_room", f

app/views/matches/edit.html.haml
- provide :title, t("match.edit")
-#%h1= t("user.edit")+" "+@match.

= render 'form'

.center
  = link_to t("user.show"), @match, class: "btn btn-default"
  \|
  = link_to t("user.back"), matches_path, class: "btn btn-default"

app/views/matches/index.html.haml
- provide :title, t("match.index")

%table.table.table-hover
  %thead
    %tr
      %th= t('match.name')
      %th= t('match.event')
      -#%th= t('match.players')
      %th= t('match.time')
      %th= t('match.status_name')
      -if can? :manage, Match
        %th= t("user.operations")

  %tbody
    - @matches.each do |match|
      %tr
        %td
          =link_to match_path(match) do
            =match.name
        %td
          =link_to event_path(match.event) do
            =match.event.name
        -#%td
          -#=link_to user_path(match.player1) do
            -#=match.player1.name
          -#VS 
          -#=link_to user_path(match.player2) do
            -#=match.player2.name
        %td= l match.time
        -if match.result
          %td= t('match.status.done')
          -#%td
            -#-#=link_to match_result_path(match) do
            -#=match.result.player1_score
            -#\:
            -#=match.result.player2_score
        -else
          %td= t('match.status.tobedone')
        -if can? :manage, Match
          %td
            %ul.list-inline
              %li= link_to t("user.edit"), edit_match_path(match)
              %li= link_to t("user.destroy"), match, method: :delete, data: {confirm: "Are you sure?"}
%br

-if can? :manage, Match
  =link_to t("user.new"), new_match_path, class: "btn btn-lg btn-primary", role: "button"

app/views/matches/new.html.haml
%h1= t('match.new')

= render 'form'

= link_to t('user.back'), matches_path

app/views/matches/show.html.haml
%p#notice= notice
-#%h2= t("match.info")
.center
  %h2
    = l @match.time, :format => :only_date
    = l @match.time, :format => :only_time
    = @match.event.name
    = @match.name
    -#= @match.player1.name
    -#VS
    -#= @match.player2.name

-if not @match.result
  .panel.panel-info
    .panel-heading= t('liveroom.info')
    .panel-body
      -@match.live_rooms.each do |live_room|
        %p= link_to live_room.name, live_room.url, :target => '_blank', class: 'zhibolink'

-if @match.result
  %p.lead= @match.result.description
  -#.panel.panel-info
    -#.panel-heading= t('match.result')
    -#.panel-body
    -#%table.table.table-hover.table-bordered
      -#%tbody
        -#%tr
          -#%td
            -#= t('result.player1_score')
            -#= @match.result.player1_score
        -#%tr
          -#%td
            -#= t('result.player2_score')
            -#= @match.result.player2_score
        -#%tr
          -#%td
            -#= t('result.videourl')
            -#=link_to @match.result.videourl, @match.result.videourl, :target=> '_blank'
        %tr
          %td= @match.result.description

.panel.panel-info
  .panel-heading= t('match.comments')
  -#.panel-body
  %table.table.table-hover.table-bordered
    -#%thead
      -#%tr
        -#%th= t('comment.username')
        -#%th= t('comment.content')
    %tbody#comments_list
      -@match.comments.each do |comment|
        %tr
          %td
            =comment.user_name
            \:::
            -#@
            -#= l comment.created_at
            = comment.content

-#=form_for [@match, @match.comments.build], remote: true do |f|
=form_for [@match, @match.comments.build], remote: true, html: {"data-type" => "json"} do |f|
  .form-group
    -#= f.text_field :content, class: 'form-control', placeholder: t('comment.content')
    = f.text_area :content, class: 'form-control', placeholder: t('comment.content'), rows: '4'
  .actions
    = f.submit t('comment.submit'), class: "btn btn-primary"

.center
  -if can? :manage, Match
    -if not @match.result
      =link_to new_match_result_path(@match), html_options = {class: 'btn btn-default'} do
        =t('result.new')
    -else
      =link_to edit_match_result_path(@match), html_options = {class: 'btn btn-default'} do
        =t('result.edit')
    \|
    = link_to t("user.edit"), edit_match_path(@match), class: "btn btn-default"
    -#\|
  -#= link_to t("user.back"), matches_path, class: "btn btn-default"