config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, :path => '/admin'

  comfy_route :cms, :path => '/', :sitemap => false

  get 'results/new'

  get 'results/create'

  devise_for :users
  scope "/admin" do
    resources :users
  end
  get 'welcome/index'

  resources :events
  resources :live_rooms

  resources :matches do
    resources :comments
    resource :result
  end

end

app/views/layouts/_footer.html.haml
%footer
  -#.footer
  -#<small>
    -#The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    -#by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  -#</small>
  .container
    -#.center
      -#%p= t('common.record_info')
    %nav
      %ul.nav.navbar-nav.navbar-right
        -#%li= link_to t("common.about"), "#"
        -#%li= link_to t("common.contact"), "#"
        %li
          %a{"data-toggle"=> 'modal', "data-target"=> '#aboutModal'}= t('common.about')
        %li
          %a{"data-toggle"=> 'modal', "data-target"=> '#contactModal'}= t('common.contact')


-#%button{"data-toggle"=> 'modal', "data-target"=> '#aboutModal'}= t('common.about')
.modal.fade#aboutModal{"aria-labelledby" => 'aboutModalLabel', :role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal", "aria-label" => 'Close'}
          %span{"aria-hidden" => 'true'} &times;
        %h4= t("common.about_header")
      .modal-body
        %p= t('common.about_body')

.modal.fade#contactModal{"aria-labelledby" => 'contactModalLabel', :role => "dialog"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal", "aria-label" => 'Close'}
          %span{"aria-hidden" => 'true'} &times;
        %h4= t("common.contact_header")
      .modal-body
        %p= t('common.contact_body')

app/views/layouts/_header.html.haml
%header.navbar.navbar-inverse
  .container
    = link_to "GGL 我们的赛事", welcome_index_url, {id: "logo"}
    %nav
      %ul.nav.navbar-nav.navbar-right
        -unless current_user
          -#%li= link_to t("common.sign_up"), new_user_registration_url
          %li= link_to t("common.log_in"), new_user_session_url
        -if current_user
          %li= link_to current_user.email, edit_user_registration_url
          %li= link_to t("common.log_out"), destroy_user_session_path, method: :delete
        -#%li= link_to t("common.help"), "#"
  -#-if controller_name == "welcome"
    -#.container
      -#-#%div{"role"=>"tabpanel"}
      -#%ul#myTab.nav.nav-tabs{"role"=>"tablist"}
        -#%li.active{:role=>"presentation"}
          -#= link_to t("common.home"), "#home", {role: 'tab', "aria-controls"=>"home", "data-toggle"=> 'tab'}
        -#%li{:role=>"presentation"}
          -#=link_to t("user.profile"), "#profile", {role: 'tab', "aria-controls"=>"profile", "data-toggle"=>'tab'}
        -#-if current_user.is? 'user.user_admin'
          -#%li{:role=>"presentation"}
            -#= link_to t("user.admin"), "#useradmin", {role: 'tab', "aria-controls"=>"useradmin", "data-toggle"=>"tab"}
  .container
    -#%div{"role"=>"tabpanel"}
    %ul#myTab.nav.nav-tabs{"role"=>"tablist"}
      %li{:class=>("active" if controller_name == "welcome"), :role=>"presentation"}
        = link_to t("common.home"), welcome_index_url, {role: 'tab'}
      -#%li{:class=>("active" if controller_name == "results"), :role=>"presentation"}
        -#= link_to t("common.results"), results_url, {role: 'tab'}
      -#-if can? :manage, Match
      %li{:class=>("active" if controller_name == "matches"), :role=>"presentation"}
        = link_to t("common.matches"), matches_url, {role: 'tab'}
      %li{:class=>("active" if controller_name == "events"), :role=>"presentation"}
        = link_to t("common.events"), events_url, {role: 'tab'}
      -#-if can? :manage, Comment
        -#%li{:class=>("active" if controller_name == "comments"), :role=>"presentation"}
          -#= link_to t("common.comments"), comments_url, {role: 'tab'}
      -if can? :manage, LiveRoom
        %li{:class=>("active" if controller_name == "live_rooms"), :role=>"presentation"}
          = link_to t("common.live_room"), live_rooms_url, {role: 'tab'}
      -if can? :manage, User
        %li{:class=>("active" if controller_name == "users"), :role=>"presentation"}
          = link_to t("user.list"), users_url, {role: 'tab'}

app/views/layouts/application.html.haml
-#<!DOCTYPE html>
-#%html
  -#%head
    -#-#%title= full_title(yield(:title))
    -#%title= yield(:title)
    -#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    -#= javascript_include_tag 'application', 'data-turbolinks-track' => true
    -#= csrf_meta_tags
    -#%meta{:name => "viewport", :content=>"width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    -#-#<!--[if lt IE 9]>
      -#-#<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      -#-#</script>
    -#-#<![endif]-->
  -#-#%frameset
    -#-#%frame{"src"=>"http://www.ifeng.com"}

  -#%body
    -#= render "layouts/header"

    -#.container
      -#= yield

    -#= render "layouts/footer"
    
  